### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by gmadajczak** [WereCatf/PCF8574_ESP#1]
I would like to ask you for information, how to use your library to connect Nokia 5110 LCD, eg. using Adafruit-PCD8544-Nokia-5110-LCD-Library. Is this possible?

**Comment by WereCatf** [comment]
You'd have to modify the Adafruit - library to use software bit-banging and this library. It is possible to do that, but it requires quite a bit of work, and the speed would suck ass: bit-banging SPI over bit-banged I2C would be horribly, horribly, horribly slow.

Why don't you just connect the LCD directly to the ESP's HSPI-pins?

**Comment by gmadajczak** [comment]
Thanks alt for answer!
Just after analysing of your code and other librariers I just realised,
that using PCF8574 would be to much complicated. I would liked to use I2C,
because it is nicer to connect 2 wires insted of 5 wires and use hex
adresses insted of SS pins, especially, that I have two other SPI devices
to connect. But I have to plan how to manage multiple SPI slaves using
limited number of ESP-12 pins. Maybe I can use PCF8574 as manager of SS
pins of devices. I have to check it.

2016-03-07 12:55 GMT+01:00 WereCatf notifications@github.com:

> You'd have to modify the Adafruit - library to use software bit-banging
> and this library. It is possible to do that, but it requires quite a bit of
> work, and the speed would suck ass: bit-banging SPI over bit-banged I2C
> would be horribly, horribly, horribly slow.
> 
> Why don't you just connect the LCD directly to the ESP's HSPI-pins?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WereCatf/PCF8574_ESP/issues/1#issuecomment-193220096.

## 

Grzegorz Madajczak

**Comment by WereCatf** [comment]
It is certainly possible to use the PCF8574 for SS-pins, I did that myself already. It requires a lot less modifying of libraries and the speed isn't a limitation then.
