### ISSUE TITLE
volatile for bool PCFInterruptFlag = false;

### ISSUE THREAD

**Issue by RobTillaart** [WereCatf/PCF8574_ESP#10]
In .../examples/pcf8574_arduinomicro/pcf8574_arduinomicro.ino
the variable should be made volatile as it is used both in main program and interrupt.

**Comment by farsajik** [comment]
thank you friend.

**Comment by WereCatf** [comment]
@RobTillaart Haven't seen any trouble arising from the volatile-keyword missing in my use, but I'll admit that it's good to have it there nevertheless. Thanks!
