### ISSUE TITLE
Raid16() give only 8bit back, not 16bit?

### ISSUE THREAD

**Issue by pvdw0310** [WereCatf/PCF8574_ESP#11]
I'am using the pcf8575 with the library with success, except the read16() function is not working properly. I get only the 8 low ports back and the 8 high ports are zero. Any idea what to do to resolve the problem. Many thanks, Peter

**Comment by WereCatf** [comment]
It works fine for me, but I just did some cleanup on the code -- it shouldn't affect anything, but give it a try anyways?

**Comment by WereCatf** [comment]
Oh, did you initialize the class with `PCF857x pcf8574(0x20, &Wire, true);` or just `PCF857x pcf8574(0x20, &Wire);` ? You need to supply three parameters to use the 16-pin PCF8575, otherwise the library defaults to the 8-pin PCF8574 and that could be your issue.

**Comment by pvdw0310** [comment]
Oeps, I found the problem. I had only a 8bit relayboard connected to the pcf8575 and there was nothing connected to the upper 8 bit ports. Now I connected also the upper ports and I works fine. Sorry for the trouble. I Like your work and happy to use it. Many thanks for the quick answer.

**Comment by WereCatf** [comment]
@pvdw0310 I was just going to reply, but it's good to know you got it working 😃 I'll just close this issue then!
