### ISSUE TITLE
Strange behaviour with PCF8575

### ISSUE THREAD

**Issue by FernandoGarcia** [WereCatf/PCF8574_ESP#12]
Hi!

This library has a strange behaviour. On code below uncomment `Wire.begin()` and the code won't work anymore.

```c
#include <pcf8574_esp.h>

PCF857x PCF8575(0x20, &Wire, true);
bool state = false;

void setup() {

  Serial.begin(115200);
  
  // Wire.begin();
  // Wire.setClock(400000);

  PCF8575.begin();
}

void loop() {

  for (byte i = 0; i < 16; i++)
  {
    state = !state;  
    PCF8575.write(i, state);

    if (PCF8575.read(i) == 1)
    {
      Serial.print("Pin ");
      Serial.print(i);
      Serial.print(" is ");
      Serial.println("HIGH");
    }
    else
    {
      Serial.print("Pin ");
      Serial.print(i);
      Serial.print(" is ");
      Serial.println("LOW");
    }
  }

  Serial.println("---------------- \n");

  Serial.println(PCF8575.read16(), BIN);

  Serial.println("---------------- \n");

  delay(1000);
}
```

The result for this code should be:

```c
Pin 0 is HIGH
Pin 1 is LOW
Pin 2 is HIGH
Pin 3 is LOW
Pin 4 is HIGH
Pin 5 is LOW
Pin 6 is HIGH
Pin 7 is LOW
Pin 8 is HIGH
Pin 9 is LOW
Pin 10 is HIGH
Pin 11 is LOW
Pin 12 is HIGH
Pin 13 is LOW
Pin 14 is HIGH
Pin 15 is LOW
---------------- 

101010101010101
---------------- 
```
Uncommenting `Wire.begin()` the result is:

```c
Pin 0 is LOW
Pin 1 is LOW
Pin 2 is LOW
Pin 3 is LOW
Pin 4 is LOW
Pin 5 is LOW
Pin 6 is LOW
Pin 7 is LOW
Pin 8 is LOW
Pin 9 is LOW
Pin 10 is LOW
Pin 11 is LOW
Pin 12 is LOW
Pin 13 is LOW
Pin 14 is LOW
Pin 15 is LOW
---------------- 

0
---------------- 
```

Best regards.

**Comment by WereCatf** [comment]
Why is it so strange? It doesn't set up the wire-instance, it expects you to set it up; there are many boards with multiple wire-instances and some of them allow you to even change the default-pins, so it's more flexible to expect you to set the instance how you like.

**Comment by FernandoGarcia** [comment]
Please check my post again.

The problem exactly is: I can't set up the **wire-instance** on code. 

Without call `Wire.begin()` the library works. 

After call `Wire.begin()` on setup it doesn't work anymore.

On code is not needed add `#include<Wire.h>` because the library does it.

After receive your PCF8575 have you tested it?

**Comment by WereCatf** [comment]
Nevertheless, the problem is not with this library; it does not call Wire.begin() anywhere, it does not set up a Wire-instance anywhere. Something else seems to set up a wire-instance and breaks when Wire.begin() is called a second time, so you need to ask whoever maintains your Wire-library about it.

**Comment by FernandoGarcia** [comment]
I'm using `Wire.h` from Arduino IDE with Arduino Mega and it works fine with others libraries.

**Comment by WereCatf** [comment]
And? What do you expect me to do about it? This library **does not create a new Wire-instance or set one up** so there is nothing I can do.

**Comment by FernandoGarcia** [comment]
Nothing, I'm sorry. 
Other maintainer could try reproduce the error but you are not interested.

**Comment by WereCatf** [comment]
You still haven't explained what good would it do for me to try and reproduce the issue, since the issue isn't in this library, but fine:

ESP8266: WORKS
ESP32: WORKS
Arduino Micro: WORKS
Arduino Due: WORKS
Arduino Uno: WORKS
STM32F103C8T6: WORKS
Attiny85: WORKS

**Comment by FernandoGarcia** [comment]
For you nothing!

I think you don't know the purpose of issues section here or you are not interested in bug reports.

If you don't want be bothered by it you should close the issues section here.

In case someone else is interested here a gif showing the problem.

![pcferror](https://user-images.githubusercontent.com/2778501/47270187-4ceba380-d53e-11e8-9ec3-bf1e32accef1.gif)

The problem is the same with Arduino IDE. The code is above.

**Comment by WereCatf** [comment]
All right, I'm locking the conversation. You clearly just wish to rage, instead of listening to what's being said to you or providing anything useful.
