### ISSUE TITLE
Support PCF8575

### ISSUE THREAD

**Issue by fredericplante** [WereCatf/PCF8574_ESP#3]
http://www.ti.com/lit/ds/symlink/pcf8575.pdf

You should push your project one step higher. The 16bit version is getting commons these days.

**Comment by WereCatf** [comment]
Hm, well, I'll suppose I'll need to buy one and add support for it. Takes 3-5 weeks to ship here, though :/

Good tip, anyways.

**Comment by fredericplante** [comment]
I got one under hand, I can maybe give some time. :D

**Comment by fredericplante** [comment]
Might as well integrate the PCF8591, all in one package. I will check on this.

**Comment by Toshibass** [comment]
I also have pcf8575 and would like to use it with wemos di mini, so I look forward to you writing this library, I will keep checking back here in hope<< thanks

**Comment by WereCatf** [comment]
I haven't yet received the PCF8575 I ordered, but it will hopefully arrive this week. Adding support for it shouldn't require a lot of work, as long as I have the device to test with.

**Comment by fredericplante** [comment]
Nah, it's not much, it's basically simply sending/receiving 2 byte instead of 1

**Comment by WereCatf** [comment]
Still waiting for my modules, Chinaman forgot to actually send what I ordered..

**Comment by WereCatf** [comment]
@fredericplante @Toshibass I got tired of waiting for the module and wrote the code following the specsheet. It should work, but for now it's untested. I'm closing this issue, open another one if it doesn't work as it should.
