### ISSUE TITLE
Great work but

### ISSUE THREAD

**Issue by fredericplante** [WereCatf/PCF8574_ESP#4]
2 thumbs up But How about adding the interruption pin function? Want me to do it?

**Comment by WereCatf** [comment]
I don't really see the point in adding such in the library. Literally everything one needs is to write a single function and use attachInterrupt() on the pin they want to use for this, and adding that in the library doesn't really make anything any easier.

**Comment by WereCatf** [comment]
This is not to say that I wouldn't accept a pull-request: by all means, if you wish to do it, then go ahead. Just make it optional, as not everyone will be using an interrupt with these at all.

**Comment by fredericplante** [comment]
Yeah I was checking you example  code and saw that. ;) But you know there are people that like when the library call an external event, look neater. Yeah, I will check to see if I can add an extra constructor that will toggle the internal handling of the interrupt. I will make it transparent.

Then fuse your libraries in the ESP VS1053 Radio project that can be found [Esp-radio](https://github.com/Edzelf/Esp-radio). It is more then obvious that your libraries will bring great benefits to this project.

**Comment by fredericplante** [comment]
Thanx
